apiVersion: v1
kind: Service
metadata:
  name: {{ include "bunkerweb.fullname" . }}-internal
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    bunkerweb.io/component: "bunkerweb"