{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: redis-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    bunkerweb.io/component: "redis"
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
{{- end }}