{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 4 }}
        bunkerweb.io/component: "redis"
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: Always
          {{- if .Values.redis.enabled -}}
          command: ["redis-server"]
          args: ["--requirepass", "$(REDIS_PASS)"]
          env:
            - name: "REDIS_AUTH"
              value: "{{ .Values.redis.config.password }}"
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    bunkerweb.io/component: "redis"
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
{{- end }}