apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        {{- with .Values.scheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        bunkerweb.io/component: "scheduler"
    spec:
      serviceAccountName: {{ include "bunkerweb.fullname" . }}
      containers:
        - name: bunkerweb-scheduler
          image: {{ .Values.scheduler.repository }}:{{ .Values.scheduler.tag }}
          imagePullPolicy: {{ .Values.scheduler.pullPolicy }}
          {{- with .Values.scheduler.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12}}
          {{- end }}
          env:
            # Mandatory for k8s integration
            - name: KUBERNETES_MODE
              value: "yes"
            - name: DATABASE_URI
              value: "{{ include "bunkerweb.databaseUri" . }}"
            {{- if .Values.settings.ui.wizard }}
            - name: UI_HOST
              value: "http://ui-{{ include "bunkerweb.fullname" . }}:7000"
            {{- end }}
            {{- include "bunkerweb.redisEnv" . | nindent 12 }}
            {{- if .Values.scheduler.extraEnvs }}
              {{- toYaml .Values.scheduler.extraEnvs | nindent 12 }}
            {{- end }}